env: "dev"
connection_string: "postgres://phenirain:phenirain13%29@localhost5432/FourthCourseFirstProject?sslmode=disable"
secret: "fourthcoursefirthproject"
allowed_origins:
    - https://app.example.com
    - https://admin.example.com
    - https://phenirain.ru
    - http://phenirain.ru
    - http://localhost:3000
http:
  port: 8081
  timeout: 15m
